### ISSUE TITLE
Implementar suporte a variáveis

### ISSUE THREAD

**Issue by leonelsanchesdasilva** [DesignLiquido/FolEs#111]
Exemplo:

```scss
$cor-base: #c6538c;

.alerta {
  borda: 1px sólida $cor-base;
}
```

Traduz para:

```css
.alert {
  border: 1px solid #c6538c;
}
```
