### ISSUE TITLE
Lógica para ler um seletor de classe

### ISSUE THREAD

**Issue by leonelsanchesdasilva** [DesignLiquido/FolEs#8]
Por exemplo:

```css
.minha-classe {
    tamanho-fonte: 16px;
    largura-maxima: 20cm;
}
```

Deve retornar:

```css
.minha-classe {
        font-size: 16px;
        max-width: 20cm;
}
```
